# Generated by Django 4.0.6 on 2022-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishDate',
            field=models.DateField(default='August 05, 2022'),
        ),
    ]
