# Generated by Django 4.0.6 on 2022-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
