# Generated by Django 4.0.6 on 2022-08-06 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.TextField(default='default-blog-img.jpeg'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publishDate',
            field=models.DateField(default=datetime.date(2022, 8, 6)),
        ),
    ]
